baseURL = "http://example.org/"
languageCode = "en-us"
paginate = 6
theme = "portio"
title = "tiips"
  # Main Menu
  [[menu.main]]
    name = "Home"
    url = "#home"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "#about"
    weight = 2
  [[menu.main]]
    name = "Service"
    url = "#service"
    weight = 3
  [[menu.main]]
    name = "Work"
    url = "#portfolio"
    weight = 4
  [[menu.main]]
    name = "Resume"
    url = "#resume"
    weight = 5
  [[menu.main]]
    name = "Blog"
    url = "#blog"
    weight = 6
  [[menu.main]]
    name = "Contact"
    url = "#contact"
    weight = 7

  # Sitemap Menu
  [[menu.sitemap]]
    name = "About me"
    url = "about"
    weight = 1
  [[menu.sitemap]]
    name = "Frequently Ask Question"
    url = "#"
    weight = 2
  [[menu.sitemap]]
    name = "Privacy & Policy"
    url = "#"
    weight = 3
  [[menu.sitemap]]
    name = "Latest Article"
    url = "#"
    weight = 4

# Preloader
[params.preloader]
enable = true
preloader = "" # use .png , .svg or .gif format
gif= "images/6.gif"

[params]
  blogPageURL = "blog"
  contactLink = "contact"
  copyright = "All right reserved copyright © tiips 2020"
  footerLogo = "images/contact/logo-white.svg"
  formspreeURL = "YOUR FORMSPREE URL"
  googleAnalytics = "YOUR GOOGLE ANALYTICS CODE"
  logo = "images/site-navigation/logo.svg"

  [params.address]
    address = "Lion Rock 72, 1/F, InnoCentre,"
    street = "72 Tat Chee Avenue, Kowloon Tong,"
    city = "Hong Kong"
    email = "hello@tiips.com"
    openingHours = "Open from 10am to 6pm (close at 5pm Sundays)"
 
  [params.map]
    APIkey = "YOUR GOOGLE MAP API"
    latitude = "23.7783741"
    longitude = "90.3746808"
    pinImage = "images/pin.png"
  
